client_id: "3MVG9PE4xB9wtoY9IbhNtYSuAVOegE_yR6h8s4fwIITYduuN1V8Tt84iUykgOM_X3lj7md_cCbNBlsN6D6LSc"
client_secret: "3006740022073476903"
username: "monika.pingale@wework.com.qaauto"
password: "monikaPingale@123"
security_token: "l3WwT1P1u0BaUkLw8ocH5Wzp"
objects: [Contact, Account]
