source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'bower-rails'
gem 'angularjs-rails'
gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'salesforce_bulk'
gem 'databasedotcom'
gem 'rspec'
gem 'faye'
gem 'rollbar'
gem 'enziUIUtility', :path => 'src/GemUtilities/EnziUIUtility'
gem 'salesforce', :path => 'src/GemUtilities/Salesforce'
gem 'rack-cors', :require => 'rack/cors'
gem 'angular-rails-templates'
gem 'google-api-client'
gem 'pg'
gem 'enziJenkinsUtility', :path => 'src/GemUtilities/EnziJenkinsUtility'
gem 'jenkins_api_client'
gem 'restforce'
gem 'coffee-script-source', '~> 1.8.0'
gem 'enziMailUtility' , :path => 'src/GemUtilities/EnziMailUtility'
gem 'enziRestforce' , :path => 'src/GemUtilities/enziRestforce'
gem 'git'
gem 'rubyzip'
gem 'zipFileGenerator' , :path => 'src/GemUtilities/ZipFileGenerator'
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
  gem 'pry-rails'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
